inherit_from:
  - .rubocop_todo.yml
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

require:
  - rubocop-rails



AllCops:
  TargetRubyVersion: 2.6

# 例外を追加
# TODO 除外設定が適切か確認する。現状設定はcircle-ciを成功させるため。
# TO DO
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
    - 'spec/**/*'
    - 'db/*'

Rails/RakeEnvironment:
  Exclude:
    - 'lib/tasks/*'

Layout/LineLength:
  Exclude:
    - 'config/*'

Rails/BulkChangeTable:
  Exclude:
    - 'db/*'
    - 'db/migrate/*'

# allow_any_instance_ofを利用できるようにするため
RSpec/AnyInstance:
  Enabled: false
